/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package saidgame;

import java.awt.*;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.InputStream;
import java.util.Random;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.*;

/**
 *
 * @author samsu
 */
public class GameDisplay extends javax.swing.JFrame {

    private Player player;
    private LinkedListMap map;
    private JButton[] boardButtons;
    private int boardSize = 31;
    private int currentLevel = 1;
    private int totalScore = 0;  // لحفظ مجموع السكورات عبر المستويات

    /**
     * Creates new form GameDisplay
     */
    public GameDisplay() {
        initComponents();
        initGame();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        rollDiceButton = new javax.swing.JButton();
        panelBoard = new javax.swing.JPanel();
        infoLabel1 = new javax.swing.JLabel();
        labelInfo = new javax.swing.JLabel();
        labelDiceResult = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(2147483647, 2147483647));

        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel3.setText("⬅️ Click Here");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(150, 480, 140, 28);

        rollDiceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/rolldice.jpg"))); // NOI18N
        rollDiceButton.setText("Roll Dice");
        rollDiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollDiceButtonActionPerformed(evt);
            }
        });
        jPanel1.add(rollDiceButton);
        rollDiceButton.setBounds(20, 320, 192, 193);

        panelBoard.setLayout(new java.awt.GridLayout(5, 6));
        jPanel1.add(panelBoard);
        panelBoard.setBounds(515, 190, 951, 580);

        infoLabel1.setFont(new java.awt.Font("Wide Latin", 1, 48)); // NOI18N
        infoLabel1.setForeground(new java.awt.Color(255, 0, 0));
        infoLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoLabel1.setText("Treasure Hunt Game");
        jPanel1.add(infoLabel1);
        infoLabel1.setBounds(300, 40, 950, 110);

        labelInfo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelInfo.setText("Player Position: 1 | Score: 0");
        labelInfo.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                labelInfoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(labelInfo);
        labelInfo.setBounds(0, 240, 284, 25);

        labelDiceResult.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        labelDiceResult.setText("🎲 Dice Rolled: - ");
        jPanel1.add(labelDiceResult);
        labelDiceResult.setBounds(0, 280, 209, 27);

        jLabel1.setBackground(new java.awt.Color(255, 51, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Note: To play, you must click on the image of the hand that rolls the dice.");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 540, 430, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("⬆️⬆️");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 520, 174, 35);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/background1.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 1880, 1020);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rollDiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollDiceButtonActionPerformed

        // TODO add your handling code here:
        Random rand = new Random();
        int dice = rand.nextInt(6) + 1;

        // ✅ تحديث الـ JLabel في الواجهة
        labelDiceResult.setText("🎲 Dice Rolled: " + dice);

        player.move(dice, boardSize);
        updatePlayerPosition();

    }//GEN-LAST:event_rollDiceButtonActionPerformed

    private void initGame() {
        String name = JOptionPane.showInputDialog(this, "Enter your name:");
        player = new Player(name);
        player.position = 0;
        player.score = 0;
        labelInfo.setText("Player Position: 0 | Score: 0");
        map = new LinkedListMap(boardSize, currentLevel);
        boardButtons = new JButton[map.getCount()];  // ✅ التعديل هنا
        fillBoard();
        updatePlayerPosition();
    }

    private void fillBoard() {
        panelBoard.removeAll();

        // ✅ نحسب عدد الخانات فعليًا من الخريطة
        int count = 0;
        Node temp = map.getHead();
        while (temp != null) {
            count++;
            temp = temp.next;
        }

        boardButtons = new JButton[count];  // عدد الخانات الفعلي

        Node current = map.getHead();
        int i = 0;

        while (current != null) {
            JButton btn = new JButton(current.type);
            btn.setFont(new Font("Arial", Font.BOLD, 12));
            btn.setOpaque(true);
            btn.setBorderPainted(false);
            btn.setEnabled(false);

            switch (current.type) {
                case "Start":
                    btn.setBackground(Color.GREEN);
                    break;
                case "Treasure":
                    btn.setBackground(Color.YELLOW);
                    break;
                case "Trap":
                    btn.setBackground(Color.RED);
                    break;
                case "Empty":
                case "Normal":
                    btn.setBackground(Color.LIGHT_GRAY);
                    break;
                case "Earthquake":
                    btn.setBackground(new Color(96, 96, 96)); // رمادي غامق
                    break;
                case "Bomb":
                    btn.setBackground(new Color(139, 0, 0)); // أحمر داكن
                    break;
                default:
                    btn.setBackground(Color.WHITE);
                    break;
            }

            boardButtons[i] = btn;
            panelBoard.add(btn);
            current = current.next;
            i++;
        }

        panelBoard.revalidate();
        panelBoard.repaint();
    }


    private void labelInfoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_labelInfoAncestorAdded
        // TODO add your handling code here:
        if (player.position >= boardSize) {
            if (currentLevel == 1) {
                JOptionPane.showMessageDialog(this, "Level 1 Complete! Starting Level 2...");

            } else if (currentLevel == 2) {
                JOptionPane.showMessageDialog(this, "Level 2 Complete! Starting Level 3...");

            } else if (currentLevel == 3) {
                JOptionPane.showMessageDialog(this, "Game Over! Final Score: " + player.score);
                ScoreFileManager.saveScore(player.name, player.score, currentLevel);
                this.setVisible(false);
                new MainMenu().setVisible(true);
            }
        }

    }//GEN-LAST:event_labelInfoAncestorAdded

    private void updatePlayerPosition() {
        if (player.position >= boardSize) {
            switch (currentLevel) {
                case 1:
                    // حفظ سكور المستوى 1
                    ScoreFileManager.saveScore(player.name, player.score, currentLevel);
                    totalScore += player.score;
                    player.score = 0;
                    JOptionPane.showMessageDialog(this, "Level 1 Complete! Starting Level 2...");
                    startLevel(2, 30);  // عدد الخانات في المستوى الثاني
                    return;

                case 2:
                    // حفظ سكور المستوى 2
                    ScoreFileManager.saveScore(player.name, player.score, currentLevel);
                    totalScore += player.score;
                    player.score = 0;
                    JOptionPane.showMessageDialog(this, "Level 2 Complete! Starting Level 3...");
                    startLevel(3, 30);  // عدد الخانات في المستوى الثالث
                    return;

                case 3:
                    // حفظ سكور المستوى 3 وعرض النتيجة النهائية
                    ScoreFileManager.saveScore(player.name, player.score, currentLevel);
                    totalScore += player.score;
                    JOptionPane.showMessageDialog(this, "🎮 Game Over!\nYour Final Total Score: " + totalScore);
                    this.setVisible(false);
                    new MainMenu().setVisible(true);
                    return;
            }
        }

        Node currentNode = map.getNodeAt(player.position);
        if (currentNode == null) {
            return;
        }

        String type = currentNode.type;

        switch (type) {
            case "Treasure":
                player.score += 10;
                break;
            case "Trap":
                player.score -= 5;
                break;
            case "Bomb":
                // 🔊 Play explosion sound
                playSound("saidgame/sounds/explosion-312361.wav");

                // 💥 Flash board red and black
                for (int flash = 0; flash < 4; flash++) {
                    for (int i = 0; i < boardButtons.length; i++) {
                        if (boardButtons[i] != null) {
                            boardButtons[i].setBackground(flash % 2 == 0 ? Color.RED : Color.BLACK);
                        }
                    }
                    try {
                        Thread.sleep(100);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }

                // ❌ Reset score
                player.score = 0;

                // 🎯 Show ❌ on the bomb tile
                if (player.position > 0 && player.position - 1 < boardButtons.length) {
                    JButton bombTile = boardButtons[player.position - 1];
                    bombTile.setBackground(Color.BLACK);
                    bombTile.setForeground(Color.WHITE);
                    bombTile.setFont(new Font("Arial", Font.BOLD, 20));
                    bombTile.setText("❌");
                }

                JOptionPane.showMessageDialog(this, "💣 Boom! You stepped on a bomb. Your score is now 0!");
                fillBoard();
                break;

            case "Earthquake":
                // ✅ تشغيل الصوت
                playSound("saidgame/sounds/quake-and-break-99034.wav");

                // ✨ وميض الأزرار
                for (int flash = 0; flash < 4; flash++) {
                    for (int i = 0; i < boardButtons.length; i++) {
                        if (boardButtons[i] != null) {
                            boardButtons[i].setBackground(flash % 2 == 0 ? Color.DARK_GRAY : Color.LIGHT_GRAY);
                        }
                    }
                    try {
                        Thread.sleep(150);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }

                shuffleMap();
                JOptionPane.showMessageDialog(this, "🌋 Earthquake! The map has been shuffled.");
                fillBoard();
                break;

        }

        labelInfo.setText("Player Position: " + player.position + " | Score: " + player.score);

        if (boardButtons == null) {
            return;
        }

        for (int i = 0; i < boardButtons.length; i++) {
            JButton btn = boardButtons[i];
            if (btn == null) {
                continue;
            }
            if (i + 1 > boardSize) {
                continue;
            }

            Node node = map.getNodeAt(i + 1);
            btn.setFont(new Font("Arial", Font.PLAIN, 12));

            if (node != null) {
                Color bg;
                switch (node.type) {
                    case "Treasure":
                        bg = Color.YELLOW;
                        break;
                    case "DoubleTreasure":
                        bg = Color.MAGENTA;
                        break;
                    case "Trap":
                        bg = Color.RED;
                        break;
                    case "Earthquake":
                        bg = Color.GRAY;
                        break;
                    case "Whirlpool":
                        bg = Color.BLUE;
                        break;
                    case "Bomb":
                        bg = new Color(139, 0, 0);
                        break;
                    default:
                        if (node.type.startsWith("Forward")) {
                            bg = Color.CYAN;
                        } else if (node.type.startsWith("Backward")) {
                            bg = Color.ORANGE;
                        } else {
                            bg = Color.WHITE;
                        }
                        break;
                }

                btn.setBackground(bg);
                btn.setText("<html>" + node.id + "<br>" + node.type + "</html>");
            }

            if (player.position > 0 && i == player.position - 1) {
                btn.setBackground(Color.GREEN);
                btn.setFont(new Font("Arial", Font.BOLD, 18));
                btn.setText("<html>" + (i + 1) + "<br>P</html>");
            }
        }
    }

    private void shuffleMap() {
        java.util.List<Node> nodes = new java.util.ArrayList<>();
        Node current = map.getHead();

        while (current != null) {
            if (!current.type.equals("Start")) {
                nodes.add(current);
            }
            current = current.next;
        }

        java.util.Collections.shuffle(nodes);

        Node startNode = map.getHead();
        Node temp = startNode;

        for (Node node : nodes) {
            temp.next = node;
            temp = node;
        }

        temp.next = null;
    }
    
    
    public Node moveBackward(Node currentNode) {
    if (currentNode != null && currentNode.prev != null) {
        return currentNode.prev;
    }
    return currentNode;
}

    private void applySpotEffect() {
        if (player.position <= boardSize) {
            Node current = map.getNodeAt(player.position);
            if (current != null) {
                switch (current.type) {
                    case "Treasure":
                        player.score += 10;
                        break;
                    case "DoubleTreasure":
                        player.score += 20;
                        break;
                    case "Trap":
                        player.score -= 5;
                        break;
                    case "Earthquake":
                        player.position = new Random().nextInt(boardSize - 1) + 1;
                        break;
                    case "Whirlpool":
                        JOptionPane.showMessageDialog(this, "You landed on a Whirlpool! Skip one turn.");
                        return;
                    default:
                        if (current.type.startsWith("Forward")) {
                            int steps = Integer.parseInt(current.type.split(" ")[1]);
                            player.move(steps, boardSize);
                        } else if (current.type.startsWith("Backward")) {
                            int steps = Integer.parseInt(current.type.split(" ")[1]);
                            player.move(-steps, boardSize);
                        }
                        break;
                }
            }
        }  
    }

    private void startLevel(int level, int size) {   // انشا
        this.currentLevel = level;
        this.boardSize = size;
        map = new LinkedListMap(boardSize, currentLevel);
        player.position = 0;
        fillBoard();
        updatePlayerPosition();
    }

    private void playSound(String relativePath) {
        try {
            // Load the audio file as a resource from the classpath
            InputStream audioSrc = getClass().getClassLoader().getResourceAsStream(relativePath);
            if (audioSrc == null) {
                System.err.println("❌ Audio file not found: " + relativePath);
                return;
            }

            // Wrap the stream to make it readable for the audio system
            InputStream bufferedIn = new BufferedInputStream(audioSrc);
            AudioInputStream audioIn = AudioSystem.getAudioInputStream(bufferedIn);

            // Load the clip and play it
            Clip clip = AudioSystem.getClip();
            clip.open(audioIn);
            clip.start();
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
        
       
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameDisplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel infoLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelDiceResult;
    private javax.swing.JLabel labelInfo;
    private javax.swing.JPanel panelBoard;
    private javax.swing.JButton rollDiceButton;
    // End of variables declaration//GEN-END:variables
}
