/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package saidgame;

import javax.swing.*;
import java.io.*;
import java.util.*;
/**
 *
 * @author samsu
 */
public class ScoreBoard extends javax.swing.JFrame {

    /**
     * Creates new form ScoreBoard
     */
    public ScoreBoard() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        scoreArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(2147483647, 2147483647));
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 255));
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1030, 190, 230, 40);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Write your username:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(490, 190, 220, 23);

        usernameField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(usernameField);
        usernameField.setBounds(740, 190, 240, 40);

        scoreArea.setColumns(20);
        scoreArea.setRows(5);
        jScrollPane1.setViewportView(scoreArea);

        jScrollPane2.setViewportView(jScrollPane1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(510, 240, 465, 400);

        jLabel2.setFont(new java.awt.Font("Wide Latin", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Search in the score");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(410, 70, 830, 49);

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 255));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(784, 680, 190, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/background1.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-220, 0, 1930, 870);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String username = usernameField.getText().trim();
        if (username.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a username.");
            return;
        }

        File file = new File("score.txt");
        if (!file.exists()) {
            JOptionPane.showMessageDialog(this, "Score file not found.");
            return;
        }

        List<ScoreRecord> allScores = new ArrayList<>();
        Map<String, Integer> levelScores = new HashMap<>();
        List<Integer> userScores = new ArrayList<>();

        try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
            String line;
            while ((line = reader.readLine()) != null) {
                if (!line.contains("|")) continue;
                String[] parts = line.split("\\|");
                if (parts.length < 3) continue;
                String user = parts[0].trim();
                int score = Integer.parseInt(parts[1].replace("Score:", "").trim());
                int level = Integer.parseInt(parts[2].replace("Level Reached:", "").trim());

                allScores.add(new ScoreRecord(user, score, level));
                if (user.equalsIgnoreCase(username)) {
                    userScores.add(score);
                    levelScores.put("Level " + level, score);
                }
            }
        } catch (IOException | NumberFormatException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error reading score file.");
            return;
        }

        if (userScores.isEmpty()) {
            scoreArea.setText("No scores found for user: " + username);
            return;
        }

        allScores.sort((a, b) -> Integer.compare(b.score, a.score));

        StringBuilder sb = new StringBuilder();
        sb.append("All Scores (High to Low):\n");
        for (ScoreRecord rec : allScores) {
            sb.append(rec.username).append(" | Score: ").append(rec.score).append(" | Level Reached: ").append(rec.level).append("\n");
        }

        sb.append("\nUser: ").append(username).append("\n");
        sb.append(" > Best Score: ").append(Collections.max(userScores)).append("\n");
        sb.append(" > Worst Score: ").append(Collections.min(userScores)).append("\n");
        sb.append(" > Level 1 Score: ").append(levelScores.getOrDefault("Level 1", 0)).append("\n");
        sb.append(" > Level 2 Score: ").append(levelScores.getOrDefault("Level 2", 0)).append("\n");
        sb.append(" > Level 3 Score: ").append(levelScores.getOrDefault("Level 3", 0)).append("\n");

        scoreArea.setText(sb.toString());
    

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private static class ScoreRecord {
        String username;
        int score;
        int level;

        public ScoreRecord(String username, int score, int level) {
            this.username = username;
            this.score = score;
            this.level = level;
        }
   
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScoreBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScoreBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScoreBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScoreBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScoreBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea scoreArea;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
